server:
  port: 8081
springdoc:
  swagger-ui:
    path: /api/v1/userServices/swagger-ui
  api-docs:
    path: /api/v1/userServices/v2/api-docs
spring:
  profiles:
    active: local
  config:
    import: configserver:http://localhost:8888
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/micro_user_service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

ratingservice:
  url: http://localhost:8083/api/v1/ratingService/
hotelservice:
  url: http://localhost:8082/api/v1/hotelServices/

# configurations for actuator

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      base-path: /api/v1/userServices/actuator
      exposure:
        include: health,*
  endpoint:
    health:
      show-details: always

# configuration for resilience4j
resilience4j:
  ratelimiter:
    instances:
      userRateLimiter:
        limit-refresh-period: 10s
        limit-for-period: 2
        timeout-duration: 2s
  retry:
    instances:
      ratingHotelServiceRetry:
        max-attempts: 3
        wait-duration: 3s
  circuitbreaker:
    instances:
      ratingHotelServiceCircuitBreaker:
        recordExceptions:
          - org.springframework.web.client.ResourceAccessException
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED