server:
  port: 8083
spring:
  application:
    name: RATING_SERVICE
  data:
    mongodb:
      url: mongodb://localhost:27017
      database: microservices
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka