server:
  port: 8083
spring:
  data:
    mongodb:
      url: mongodb://localhost:27017
      database: microservices
#    url: jdbc:mysql://localhost:3306/micro_user_service
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true