server:
  port: 8083
springfox:
  documentation:
    swagger:
      v2:
        path: /api/v1/ratingService/v2/api-docs
spring:
  profiles:
    active: local
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: RATING-SERVICE
  config:
    import: configserver:http://localhost:8888
  data:
    mongodb:
      url: mongodb://localhost:27017
      database: microservices
eureka:
  instance:
    statusPageUrlPath: api/v1/ratingService/actuator
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka